### ISSUE TITLE
active-win doesn't work on Windows 32 bits (because of fastcall). Should we change to node-ffi (as it does work)?

### ISSUE THREAD

**Issue by tiangolo** [sindresorhus/active-win#10]
Here's [the issue in `fastcall`](https://github.com/cmake-js/fastcall/issues/17). By the owner comments, it seems like is not something easy or fast to solve.

In that issue is described the procedure to reproduce it, I won't copy all the steps here, they include downloading a free Windows 7 32 bit virtual machine, etc.

---

Also, `fastcall` uses `cmake-js`, which is a "not so standard" way to build a Node extension. So, for example, to support Electron we would have to change the README to [include those instructions for a cmake-js dependent package](https://github.com/cmake-js/cmake-js#electron). That's not a big deal, it can be done, but could be somewhat cumbersome for users, as we would have to explain what is happening. (Assuming we just remove support for Windows 32 bits).

But because of that same only `package.json` configuration, we couldn't support other ways of building the package, for example with [`electron-builder`](https://github.com/electron-userland/electron-builder). It rebuilds all the dependencies for `x64` and for `ia32` automatically, using the needed runtime (Electron), and then packages both in a single installer, but it wouldn't be able to do that for a `cmake-js` dependent package, as it would have to have the configurations in the `package.json`. This problem would be the next to happen assuming that the first issue was solved and `cmake-js` / `fastcall` gave support for Windows 32 bit systems.

My intention was to include `cmake-js` support into `electron-builder`, here: https://github.com/cmake-js/cmake-js/issues/83 and here: https://github.com/electron-userland/electron-builder/issues/1516 .

But I won't be able to continue with that plan, as I can't even test it, because of that first issue above.

---

Meanwhile, I created a branch, and I changed all the `fastcall` code to `node-ffi`, and:

* It works in Windows 32 bits too.
* It can be built by `electron-builder` automatically, supporting a single installer for 64 and 32 systems (it can be built in a 64 bit Windows machine and support 64 and 32 bits).
* It doesn't require the users to add a special section in their `package.json` to be able to use this package.

I tested it all with that VM procedure described above.

---

What do you think about changing `active-win` back to `node-ffi` instead of `fastcall`? 

My opinion is that the speed improvement is not that a big deal for this specific package, it is not doing computationally expensive operations. 

But I do think that it would be a plus giving better support for some OSes (Windows 32 bits), better support for Electron and similar tools right out of the box and support for `electron-builder` including building a single installer for both architectures. 

I can PR my branch at https://github.com/tiangolo/active-win/tree/ffi . It's the one I'm using right now, as I need those features.

**Comment by sindresorhus** [comment]
I don't really care about 32-bit and I personally think people should just move to 64-bit, but I do realize you have business constraints, so sure.

**Comment by tiangolo** [comment]
I actually do think that too! I'm on Ubuntu for some time now, and in 64 bits since years...

And I was wishing I could just ditch 32 bit. But then I did some "analytics" on the user base of what we are building and I found out that more than half the users are in a a 32 bit system yet :cry: 

So I imagine that many developers that use this package could need to support those architectures too... :disappointed:

**Comment by sindresorhus** [comment]
> And I was wishing I could just ditch 32 bit. But then I did some "analytics" on the user base of what we are building and I found out that more than half the users are in a a 32 bit system yet 😢

That's the beauty of doing free open-source products, [I can decide not to care.](https://github.com/sindresorhus/caprine/releases/tag/v2.2.0)

**Comment by tiangolo** [comment]
Hehe

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/active-win/commit/7684e2f45755144adf99a5cd7525848cac5da8f6
