### ISSUE TITLE
Macos Incorrect URL when chromium is open

### ISSUE THREAD

**Issue by pawankanumalli** [sindresorhus/active-win#113]
In MacOS when you have a chromium instance running alongside the regular Google Chrome browser, the URL property always returns chrom://newtab or the url of the Chromium instance which is not in the Foreground.

Steps to reproduce.

1) Run your electron app with active-win

2) Open Google Chrome and browse a website

3) Open your chromium instance, [i opened a new chromium instance while testing a puppeteer code and left it open and thats how i discovered this Bug]

4) Check the log of active-win, you will find all the details of the actual Google Chrome tab, but the URL will be of the Chromium instance

Sample Log

Activity:{"memoryUsage":1232,"bounds":{"y":25,"height":803,"x":0,"width":1440},"title":"sindresorhus/active-win: Get metadata about the active window (title, id, bounds, owner, etc)","url":"chrome://newtab/","id":10596,"owner":{"processId":371,"bundleId":"com.google.Chrome","name":"Google Chrome","path":"/Applications/Google Chrome.app"},"platform":"macos"}

**Comment by pawankanumalli** [comment]
@sindresorhus could you please look into this issue.

**Comment by sindresorhus** [comment]
I think this was fixed by https://github.com/sindresorhus/active-win/releases/tag/v7.5.0
