### ISSUE TITLE
activeWindow.url returns undefined in electron production app, but works perfectly in development mode

### ISSUE THREAD

**Issue by ganeshpartheeban** [sindresorhus/active-win#114]
I'm using Electron 11.4.7 & active-win 7.1.0

No issues while retrieving URL from .url in development mode.
But .url returns undefined in production mode.

**Comment by tkainrad** [comment]
I believe your problem is that your app does not have the required automation permissions. See [my answer in another issue for more details](https://github.com/sindresorhus/active-win/issues/99#issuecomment-870404613).

**Comment by ganeshpartheeban** [comment]
Closing this issue. Check this comment for the correct procedure to fetch URL on Mac

https://github.com/sindresorhus/active-win/issues/99#issuecomment-870874546
