### ISSUE TITLE
Using app name for AppleScript url access breaks when users change the name of their browser app

### ISSUE THREAD

**Issue by wrgoto** [sindresorhus/active-win#117]
We're currently using AppleScript to get the URL from apps by referencing the app name in the script. I've noticed that changing the name of the browser causes this functionality to break. As an example, if I rename 'Google Chrome' to just 'Chrome' on my mac, it'll break active-win's ability to grab the URL from Chrome.

I think there are a couple of ways we can tackle this issue. The first would be to use the bundle ids of the application to reference the app, though I'm not entirely sure AppleScript can do this.

The other would be to take a functional approach to try to grab the URL of the app regardless of what app it is. If it fails, then catch the failure and return null. This would be nice as it would work out of the box with all browsers (as long as they support the same paradigms of providing the URL) and avoid having to add each one individually.

**Comment by sindresorhus** [comment]
Yeah, we should use bundle identifiers instead.

**Comment by sindresorhus** [comment]
> The other would be to take a functional approach to try to grab the URL of the app regardless of what app it is.

AppleScript comes with some overhead, so I don't think we should execute it regardless.
