### ISSUE TITLE
In Mac it's working. But in  window 10 it's not working.

### ISSUE THREAD

**Issue by basantsd** [sindresorhus/active-win#126]
In Mac it's working.
But in  window 10 it's not working.
1 error : UnhandledPromiseRejectionWarning: Error: Cannot find module 'ffi-napi'
![IMG20211009014425](https://user-images.githubusercontent.com/34518191/136620040-71df7451-ab38-453b-9804-6369d8ae736b.jpg)

2 error : UnhandledPromiseRejectionWarning: Error: Cannot find module 'ref-wchar-napi'
![IMG20211009014425](https://user-images.githubusercontent.com/34518191/136620130-c256c22b-040e-41d6-9f1d-303daa6e0ab8.jpg)

![IMG20211009014358](https://user-images.githubusercontent.com/34518191/136620107-f0116524-b56f-4f1b-aa10-c34abdedee60.jpg)

**Comment by supercoww** [comment]
Some of the dependencies of active-win require python and visual studio build tools when developing on windows.
You can install them by following this: https://github.com/nodejs/node-gyp#on-windows. Then run:
```
npm install
```
If you are using active-win in electron, run this after install.
```
npx electron-rebuild
```
