### ISSUE TITLE
Getting error while updating Node Modules

### ISSUE THREAD

**Issue by Nickonit92** [sindresorhus/active-win#129]
1: 00007FF646A630AF v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112511
 2: 00007FF6469F2216 DSA_meth_get_flags+65542
 3: 00007FF64697D689 std::basic_ostream<char,std::char_traits<char> >::operator<<+51513
 4: 00007FF6472DF5D6 v8::internal::Builtins::code_handle+172694
 5: 00007FF6472DF1C9 v8::internal::Builtins::code_handle+171657
 6: 00007FF6472DF48C v8::internal::Builtins::code_handle+172364
 7: 00007FF6472DF2F0 v8::internal::Builtins::code_handle+171952
 8: 00007FF6473B2641 v8::internal::SetupIsolateDelegate::SetupHeap+494673
 9: 00007FF647344AEE v8::internal::SetupIsolateDelegate::SetupHeap+45310
10: 00007FF647344AEE v8::internal::SetupIsolateDelegate::SetupHeap+45310
11: 00007FF6473747C3 v8::internal::SetupIsolateDelegate::SetupHeap+241107
12: 00007FF6473FADD2 v8::internal::SetupIsolateDelegate::SetupHeap+791522
13: 00007FF6473669FA v8::internal::SetupIsolateDelegate::SetupHeap+184330
14: 00007FF647342BFB v8::internal::SetupIsolateDelegate::SetupHeap+37387
15: 00007FF64722366B v8::internal::Execution::CallWasm+1563
16: 00007FF64722378B v8::internal::Execution::CallWasm+1851
17: 00007FF64722423A v8::internal::Execution::TryCall+378
18: 00007FF6472005EA v8::internal::MicrotaskQueue::RunMicrotasks+410
19: 00007FF64720038A v8::internal::MicrotaskQueue::PerformCheckpointInternal+74
20: 00007FF646A914F6 node::CallbackScope::~CallbackScope+710
21: 00007FF646A9129E node::CallbackScope::~CallbackScope+110
22: 00007FF646A28608 node::Start+1992
23: 00007FF646A8F009 node::LoadEnvironment+89
24: 00007FF6469AAB83 cppgc::internal::NormalPageSpace::linear_allocation_buffer+53811
25: 00007FF646A27F1D node::Start+221
26: 00007FF6468488CC RC4_options+348108
27: 00007FF6478A3A88 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+14472
28: 00007FFE332454E0 BaseThreadInitThunk+16
29: 00007FFE3442485B RtlUserThreadStart+43

**Comment by sindresorhus** [comment]
You're gonna have to do some debugging yourself. There's nothing I can do based on this info. Ensure you're on the latest version of Node.js and this package.

**Comment by sindresorhus** [comment]
You're gonna have to do some debugging yourself. There's nothing I can do based on this info. Ensure you're on the latest version of Node.js and this package.
