### ISSUE TITLE
activeWindow returns a process name instead of a product name to windows owner.name

### ISSUE THREAD

**Issue by pityulin** [sindresorhus/active-win#130]
In Windows, when getting information about the active window, the process name is returned instead of the "normal" product name

For example, for the Chrome browser it returns
owner.name = "crome.exe" instead of "Google Chrome"

**Comment by hanspagel** [comment]
Seems to apply to macOS aswell: `Slack.app` instead of `Slack`

<img width="454" alt="Bildschirmfoto 2022-01-26 um 22 37 35" src="https://user-images.githubusercontent.com/1577992/151323042-81bcd8de-8ead-49a1-a7f6-25b3cf8c3ebb.png">
