### ISSUE TITLE
Error: No native build was found for...

### ISSUE THREAD

**Issue by augustnmonteiro** [sindresorhus/active-win#132]
Error: No native build was found for platform=win32 arch=x64 runtime=electron abi=99 uv=1 libc=glibc node=16.9.1 electron=16.0.6 webpack=true

Node=v16.13.2
NPM=8.3.0
Electron-forge=6.0.0-beta.63

**Comment by sindresorhus** [comment]
This is not the place to ask for Electron-forge support.
