### ISSUE TITLE
Uses a lot of cpu resources

### ISSUE THREAD

**Issue by yusbel80** [sindresorhus/active-win#133]
Running this on my mac pro and constantly using cpu % ~ 30-40%

**Comment by sindresorhus** [comment]
How are you running it? This is a command-line tool that is not long-running.

**Comment by sindresorhus** [comment]
That is your problem. You are polling it way too often. It's not a super heavy operation, but running it once a second is gonna use a lot of CPU.

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/sindresorhus/active-win/issues/1
