### ISSUE TITLE
Mention in the docs to include "postinstall": "install-app-deps"

### ISSUE THREAD

**Issue by aRestless** [sindresorhus/active-win#14]
Basically I spent two days fiddling around with the package, hitting errors like this when running it in Electron on Windows:

`Error: error: 1114\\?\D:\path\to\project\node_modules\ref\build\Release\binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (D:\path\to\project\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (D:\path\to\project\node_modules\ref\lib\ref.js:5:47)
`

along with a localized message that a DLL initialization routine would have failed. 

I finally found out the package worked fine after I had built an Electron release package once, which finally led me to including `"postinstall": "install-app-deps"` in the  `"scripts"` section of my package.json.

Granted, I'm an absolute NodeJS/Electron beginner and more experienced devs (or the smart ones using the Electron boilerplate) might not run into this issue, but I certainly would have appreciated a mention of this in the docs.

**Comment by sindresorhus** [comment]
> Mention in the docs to include "postinstall": "install-app-deps"

That's specific to your usage of Electron Builder and has nothing to do with this module.

This is also clearly documented at the top of the docs of Electron Builder.

**Comment by aRestless** [comment]
> That's specific to your usage of Electron Builder and has nothing to do with this module.

I learned by now that install-app-deps is an electron-builder specific command - but the issue persists with electron, install-app-deps is just one way of solving it with electron-builder.

Documenting this here for others to find.

Consider the following package.json:

```
{
  "name": "active-win-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "electron": "^1.6.11"
  },
  "dependencies": {
    "active-win": "^2.0.0"
  }
}
```

And the following index.js:

```
require("active-win")();
```

Commands:
```
npm install
./node_modules/.bin/electron .
```

Will result in the error posted above. While

```
node .
```

will run through fine. So yeah, it seems to be an issue how electron handles native dependencies in general - the reliance on electron-builder for this part is a bit weird to me. I understood electron-builder as an optional, additional package to use for distribution, not for building your dependencies while developing.

But well, even though the problem isn't directly linked to your package, maybe this Issue helps someone in the future who takes the same path as me.

To finally sum up: To get rid of this error when using electron, add `electron-builder` to your dev-dependencies (`npm install electron-builder --save-dev`), add `"postinstall": "install-app-deps"` to the `"scripts"` section of your package.json, resulting in something like this:

```
{
  "name": "active-win-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
  "postinstall": "install-app-deps",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "active-win": "^2.0.0"
  },
  "devDependencies": {
    "electron": "^1.6.11",
    "electron-builder": "^19.6.0"
  }
}
```

Finally, run `npm install` again and you'll be fine.
