### ISSUE TITLE
`getOpenWindows` does not return all windows 

### ISSUE THREAD

**Issue by nsharma1396** [sindresorhus/active-win#157]
Thanks for the amazing work on this package

I am trying to use `getOpenWindows` and though it does returns the active windows, few cases seems to get missed:

* Chrome/firefox tabs: Only the current focused chrome or firefox tab is returned instead of all open tabs (same for apps that have tabs like powershell, vscode, etc)
* Widget kind of windows are only returned in the `activeWindow` API and not the `getOpenWindows` one

Not sure if this is expected out of the API but would really appreciate if there can be some workaround for this.

Thanks

**Comment by sindresorhus** [comment]
> Chrome/firefox tabs: Only the current focused chrome or firefox tab is returned instead of all open tabs (same for apps that have tabs like powershell, vscode, etc)

Tabs are not windows, so this is expected behavior.

> Widget kind of windows are only returned in the activeWindow API and not the getOpenWindows one

What are "widget windows"? And what OS?

**Comment by nsharma1396** [comment]
> Tabs are not windows, so this is expected behavior.

Okay, that makes sense, but is there any way that can help us get all the tabs as well?

> What are "widget windows"? And what OS?

So, by hitting the Win key + W in Windows 11, you can bring up the widgets board. I was referring to that but I think that doesn't really qualify as a window again so that's alright.

**Comment by sindresorhus** [comment]
> Okay, that makes sense, but is there any way that can help us get all the tabs as well?

I'm not familiar with Windows, so I don't know whether it's possible. It feels a bit outside the scope of this package though.

> So, by hitting the Win key + W in Windows 11, you can bring up the widgets board. I was referring to that but I think that doesn't really qualify as a window again so that's alright.

It's a bug that it's included.

// @miniben-90

**Comment by RedSparr0w** [comment]
It seems that most fullscreen/fullscreen windowed windows are also excluded.

**Comment by RedSparr0w** [comment]
Just checking, did #159 also solve the issue of fullscreen windows not being detected?

**Comment by sindresorhus** [comment]
@RedSparr0w Open a new issue about that.
