### ISSUE TITLE
Get full path to executable

### ISSUE THREAD

**Issue by ahallicks** [sindresorhus/active-win#16]
Would it be possible to return the full path to the executable of the currently active application? I'd like to be able to get the icon of the app and don't know of a good way to do this based solely on having the name of the exe.

**Comment by sindresorhus** [comment]
On macOS, it should be pretty simple, but I have no idea with Windows. Pull request welcome.

**Comment by ahallicks** [comment]
Looking at the code (for Windows at least) would it not just be a case of breaking the following line out:
https://github.com/sindresorhus/active-win/blob/master/lib/windows.js#L77

And storing the next line as a separate var? That way, by the looks of it, you'd have the path and then the basename of the executable.

I'm no expert at this though so may be talking rubbish!

**Comment by sindresorhus** [comment]
This is implemented for macOS and Windows. The Linux implementation is missing though: #23

**Comment by sindresorhus** [comment]
Closing in favor of #23
