### ISSUE TITLE
activeWindow.getOpenWindows() z-index

### ISSUE THREAD

**Issue by pie6k** [sindresorhus/active-win#163]
I want to build screen capture window picker, where I create invisible overlay and you 'click' on a window you want to record, similar to default screenshot taking on mac, when selecting the window.

It is very likely a few windows occupy the same bounds or overlap each other. In such a case, to know which window you clicked, I need z-index attribute of the window. Is it possible to get it somehow? Or can I treat order of returned windows as their z-index?

**Comment by sindresorhus** [comment]
Windows are returned in order from front to back.
