### ISSUE TITLE
Incorrect Y bounds with second monitor case

### ISSUE THREAD

**Issue by RewriteH** [sindresorhus/active-win#164]
### Environment
OS: MacOS Monterey 12.6.3
PC: Second full-hd 120hz monitor connected to MacBook air with 2k display via dock.

### Problem
Window real bounds is: 
`{x: 464, y: 317, width: 762, height: 763}`

active-win bounds is: 
`{ y: 257, width: 762, height: 763, x: -1456 }`

I can calc the X position: 
```
const realX = display.size - Math.abs(bounds.x)
```
And i can calc Y position: 
```
const magicNumber = 60

const realY = bounds.y + magicNumber
```

I always need to plus magic +60 number to get correct Y axis position. Always, in any window position.

How to fix it, or how to understand what this magic number 60 is?

**Comment by sindresorhus** [comment]
The window position is fetched directly from macOS, so there's nothing we can do about it. You'll have to report this to Apple.

https://github.com/sindresorhus/active-win/blob/27221e5da0a64025bdec8759605694ea84ff9f68/Sources/ActiveWinCLI/main.swift#L34

**Comment by RewriteH** [comment]
I Found the missing piece
`display.bounds.y` is 60 

So i should include display bound in my calculations
