### ISSUE TITLE
Build and release process question

### ISSUE THREAD

**Issue by wrgoto** [sindresorhus/active-win#167]
Hey @sindresorhus, thanks for maintaining such a great library. What are the steps to build and publish the newest version? We're trying to build from our fork and have some questions. I see that when you create a release, GitHub Actions builds the Windows binaries. Do you build the macOS locally, add the Windows binaries to `lib/binding` and then publish?

**Comment by sindresorhus** [comment]
The macOS binary is built at publish time: https://github.com/sindresorhus/active-win/blob/27221e5da0a64025bdec8759605694ea84ff9f68/package.json#L38

The Windows binaries are built with GitHub Actions and automatically added to the GitHub release: https://github.com/sindresorhus/active-win/blob/main/.github/workflows/release.yml

**Comment by wrgoto** [comment]
@sindresorhus Why aren't you adding the macOS binaries to the GitHub release?

**Comment by sindresorhus** [comment]
For simplicity. It's easier to just embed it in the package.
