### ISSUE TITLE
Feature: Able to get active window other properties like positions & states

### ISSUE THREAD

**Issue by genesisneo** [sindresorhus/active-win#21]
It would be nice if this module can also get current windows positions & states.
```
{
  title: 'npm install',
  id: 32,
  app: 'Terminal',
  pid: 64,
  position: { top: 128, left: 256, bottom:568, right:320 },
  state: 'Maximized'
}
```
To change the states we can have something like `activeWin.state(['minimized', 'maximized', 'normal', 'close']);`, and to move current window we can have something like `activeWin.move(t,l,b,r);`.

**Comment by sindresorhus** [comment]
Position and size are available for macOS in master, see https://github.com/sindresorhus/active-win/issues/19. It's just waiting for implementation on Linux and Window, and docs.

**Comment by sindresorhus** [comment]
> To change the states we can have something like activeWin.state(['minimized', 'maximized', 'normal', 'close']);, and to move current window we can have something like activeWin.move(t,l,b,r);.

That's outside the scope of this module.

**Comment by sindresorhus** [comment]
Closing in favor of #23

**Comment by xudaolong** [comment]
@sindresorhus I want to know if I can just provide information about activeWin.state instead of manipulating them. Thanks.
