### ISSUE TITLE
Can't detect active window in a service

### ISSUE THREAD

**Issue by starsoftmongolia** [sindresorhus/active-win#26]
We have developed some app using active-win library. Then used nssm (https://nssm.cc) to enable  app work in background. But it could not detect active window. What is wrong, how to make it run ? Why it could not detect foreground window when app is windows service ?

**Comment by tiangolo** [comment]
What do you mean by making it run in the background? 

The link is dead, returns a 503 HTTP error.

If you are developing a desktop app, you can use Electron. With that you can make it have only a tray icon (that's what many "background" apps do). Or you can even make it run without a tray icon at all. It doesn't depend on active-win, but on Electron (or wherever you are using active-win). That's what I've done before.

Does that help?
