### ISSUE TITLE
Error when active app does not have a window (macOS)

### ISSUE THREAD

**Issue by salehhamadeh** [sindresorhus/active-win#32]
**Repro Steps**
1. Set a timeout that runs `activeWin()`
2. Open Finder
3. Close window but do not select another window
4. Wait for `activeWin()` to run

Expected: The call returns the app without the window information.

Actual: The call fails with the following error:
> SyntaxError: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at parseMac (.../node_modules/active-win/lib/macos.js:10:15)
      at <anonymous>
  (node:2458) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Error parsing window data

**Comment by kkm** [comment]
I confirm with me also happened.

**Comment by pimartin** [comment]
I've also noticed this issue and was able to reproduce it like @salehhamadeh explained.

When the `catch` clause was triggered, it appeared stdout was a string with a length of 0.

**Comment by matthewjumpsoffbuildings** [comment]
this is also happening for me.
