### ISSUE TITLE
Unable to get the activeWin working

### ISSUE THREAD

**Issue by dakshhmehta** [sindresorhus/active-win#33]
Dev mode.......... electron
 Quasar theme...... mat
 Quasar CLI........ v0.17.23
 Quasar Framework.. v0.17.19
 Debugging......... enabled

 app:quasar-conf Reading quasar.conf.js +0ms
 app:dev Checking listening address availability (0.0.0.0:8080)... +3ms
 app:webpack Extending Renderer process Webpack config +263ms
 app:webpack Extending Main process Webpack config +1ms
 app:generator Generating Webpack entry point +5ms
 app:dev-server Booting up... +1ms

  Renderer process █████████████████████████ [100%] in ~8s
  Main process                               [0%]

 ERROR  Failed to compile with 1 errors                                                                                                       17:44:35

This relative module was not found:

* ../build/Debug/iconv.node in ./node_modules/iconv/lib/iconv.js

**Comment by sindresorhus** [comment]
You haven't really provided any useful information for me to help you, but you might want to read how to use native dependencies with Electron: https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md
