### ISSUE TITLE
Provide Windows information without FFI

### ISSUE THREAD

**Issue by arciisine** [sindresorhus/active-win#35]
I'm currently using this module in a vscode plugin, and platform specific binaries are complicated to handle.  I was looking at some powershell scripts what should be able to produce the necessary information, and was wondering if you would be open to a PR that removed the use of ffi.

**Comment by arciisine** [comment]
The script I was looking at: https://gallery.technet.microsoft.com/scriptcenter/Get-the-position-of-a-c91a5f1f

**Comment by sindresorhus** [comment]
I’m happy to add support for a fallback, but anything other than native will be very slow, especially powershell. One day Node.js will have native FFI support and all will be good.

**Comment by arciisine** [comment]
Cool, I was thinking of this as a fallback, specifically for vscode plugins where I can't compile.  Well send a PR in the next few days.

**Comment by sindresorhus** [comment]
@arciisine Totally up to you. I'm happy to add you as a maintainer if you would like to maintain it here. Alternatively, we could add a link in the readme to your fork.

**Comment by arciisine** [comment]
@sindresorhus I think I'm going to fork for now, given the magnitude of change. I  want to make sure I have proper attribution, beyond the MIT license inclusion.  Is there anything specifically you would want to see regarding acknowledgement/attribution?

**Comment by sindresorhus** [comment]
That's totally fine.

> Is there anything specifically you would want to see regarding acknowledgement/attribution?

Just ensure you have proper MIT license inclusion.

**Comment by sindresorhus** [comment]
Do a PR with a link to your fork when it's out. Should be added here: https://github.com/sindresorhus/active-win#related
