### ISSUE TITLE
active-win not working after release :c

### ISSUE THREAD

**Issue by afloras** [sindresorhus/active-win#41]
Hello,

I'm pretty new at Electron and I created a software where everything works out when I use your library in debug mode.
- npm install active-win
- npm start

However, when I decide to create an exe file for Windows 64 bits, i can affirm that the following require line doesn't work (I debugged my code hard) :
const activeWin = require('active-win') // not working...

I don't catch any error though and it's just blocking the rest of my JavaScript code.

I used electron-packager to generate the production release : 
"win64": "electron-packager . --overwrite \"MyApp\" --out=dist/win64 --platform=win32 --arch=x64 --icon=./assets/build/win/icon.ico --prune=true --asar=true --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName=\"MyApp\""

Please, can you tell me if I need some dependencies to use this library in release mode ?

Thanks in advance.

**Comment by sindresorhus** [comment]
`active-win` has a dependency on packages that use native Node.js addons, which means you cannot easily cross-compile.

- https://electronjs.org/docs/tutorial/using-native-node-modules
- https://github.com/electron-userland/electron-packager/issues/215

You should try the Electron support channels for additional questions.
