### ISSUE TITLE
Dependency broken under Node 12

### ISSUE THREAD

**Issue by thirstyfish** [sindresorhus/active-win#48]
The ref package is currently broken on Node 12:
https://github.com/TooTallNate/ref/issues/107

I'm guessing this means it won't compile on the new Electron 5 on windows and this issue is related:
https://github.com/sindresorhus/active-win/issues/41

**Comment by VigneshVaidyanathan** [comment]
Any update or workaround for this?

**Comment by Janealter** [comment]
This dependency can be replaced by `ref-napi` in the main package and in `ref-wchar`, in `ref-struct`. In this case, `active-win` will work on Node 12. I checked this.

**Comment by Janealter** [comment]
I create fork with Node 12 support https://github.com/Janealter/active-win-12

**Comment by Janealter** [comment]
I created fork with Node 12 support https://github.com/Janealter/active-win-12

**Comment by Janealter** [comment]
I can make PR in this repository, if @sindresorhus needs it.

**Comment by sindresorhus** [comment]
A PR would be great.

**Comment by Janealter** [comment]
Check https://github.com/sindresorhus/active-win/pull/58

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/active-win/pull/58
