### ISSUE TITLE
Install the python dependency

### ISSUE THREAD

**Issue by VigneshVaidyanathan** [sindresorhus/active-win#52]
Hello, 

I am new to node and I am trying to get the active windows on a Windows OS. I presume in Linux and Mac, the python package is automatically installed but in Windows, it isn't. I see that one of the dependencies **ffi-napi** has a python dependency.

I want to know if there is any command that can automatically install the python dependency and configure that so the active windows will work. Any help would be really great.

**Comment by sindresorhus** [comment]
Since this is about `ffi-napi`, you should ask there.
