### ISSUE TITLE
Question: How to get browser URL

### ISSUE THREAD

**Issue by JSilversun** [sindresorhus/active-win#54]
Thank you for your awesome work. I have a question, is there a way to get the browser URL instead of just the tab title?

**Comment by albinekb** [comment]
See #45

**Comment by JSilversun** [comment]
Thanks for your response, sorry about the duplicate question

**Comment by sindresorhus** [comment]
This is now available in the latest version: https://github.com/sindresorhus/active-win/releases/tag/v6.1.0
