### ISSUE TITLE
Fresh install of the package shows errors:

### ISSUE THREAD

**Issue by pl4yradam** [sindresorhus/active-win#60]
Hi Wondering if you can assist with these errors, I've had a google about it and there doesn't seem to be resolves for windows.

- Cannot open include file: 'get-uv-event-loop-napi.h': No such file or directory in node_modules 
\ffi-napi\build\ffi_bindings.vcxproj

- hundreds of these errors:
 warning C4311: 'type cast': pointer truncation from 'char (*)[16]' t 
o 'long' (compiling source file ..\deps\libiconv\lib\iconv.c

I'm not sure what's going on, removing the active-win package removes these errors.

**Comment by sindresorhus** [comment]
The error is coming from `ffi-napi`. Try asking there instead.
