### ISSUE TITLE
Browser URL Functionality

### ISSUE THREAD

**Issue by robertjkeck2** [sindresorhus/active-win#62]
I'd love to add functionality mentioned in #45 and #54. I know #54 suggests using `node-applescript` but it is actually quite easy to add the AppleScript functionality to the existing Swift file in `active-win`. I've already tested a few ways to include the active URL in the returned JSON and could submit a PR if you'd entertain it. If not, I can just make a separate package!

**Comment by sindresorhus** [comment]
Sounds useful. PR welcome 👌

**Comment by robertjkeck2** [comment]
PR #63 submitted. Let me know if you have any questions or thoughts!

**Comment by jcpatac** [comment]
Howdy! Any chance on this functionality being implemented on Windows and Linux OS?

**Comment by codewaseem** [comment]
I would love to have this on Windows and Linux. If you don't have time for this, please guide me to the resources on how to get it done. Thanks.
