### ISSUE TITLE
Cannot run in production mode

### ISSUE THREAD

**Issue by DoshinNelson** [sindresorhus/active-win#73]
Hi all, 
I have a small piece of code that runs in development mode, but when running in production the following line gives an error. Is this related to Mac permissions on Catalina?
 var active =  (await activeWin())

Gives >
child_process.js:308 Uncaught (in promise) Error: Command failed: /Applications/electron-webpack-quick-start.app/Contents/Resources/app.asar.unpacked/node_modules/active-win/main

Thanks a lot

**Comment by sindresorhus** [comment]
You’re not packing your Electron app correctly. This is not the place to ask for support for that.

**Comment by EasonChang0115** [comment]
i am also have this problem. have any solution here?
