### ISSUE TITLE
Error while running in electron app in windows

### ISSUE THREAD

**Issue by blockchain-expert** [sindresorhus/active-win#74]
I've encountered with some error in windows. Below given is the npm log.

> 0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.12.0
3 info using node@v12.13.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle myapp@1.3.36~prestart: myapp@1.3.36
6 info lifecycle myapp@1.3.36~start: myapp@1.3.36
7 verbose lifecycle myapp@1.3.36~start: unsafe-perm in lifecycle true
8 verbose lifecycle myapp@1.3.36~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;H:\Projects\my-app\electron-ui\node_modules\.bin;C:\Program Files\Python38\Scripts\;C:\Program Files\Python38\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;G:\softwares\Yarn\bin\;C:\Program Files\Git\cmd;C:\Users\dev\.windows-build-tools\python27\;C:\Users\dev\.windows-build-tools\python27\;C:\Users\dev\.windows-build-tools\python27\;C:\Users\dev\AppData\Local\Microsoft\WindowsApps;F:\softwares\IntelliJ IDEA Community Edition 2019.1.2\bin;;C:\Users\dev\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\dev\AppData\Roaming\npm;C:\Users\dev\AppData\Local\Yarn\bin;C:\Program Files\MongoDB\Server\4.2\bin;
9 verbose lifecycle myapp@1.3.36~start: CWD: H:\Projects\my-app\electron-ui
10 silly lifecycle myapp@1.3.36~start: Args: [ '/d /s /c', 'cross-env NODE_ENV=development electron .' ]
11 silly lifecycle myapp@1.3.36~start: Returned: code: 3  signal: null
12 info lifecycle myapp@1.3.36~start: Failed to exec start script
13 verbose stack Error: myapp@1.3.36 start: `cross-env NODE_ENV=development electron .`
13 verbose stack Exit status 3
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid myapp@1.3.36
15 verbose cwd H:\Projects\my-app\electron-ui
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.13.0
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 3
22 error myapp@1.3.36 start: `cross-env NODE_ENV=development electron .`
22 error Exit status 3
23 error Failed at the myapp@1.3.36 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3, true ]

**Comment by sindresorhus** [comment]
This is not a support forum. I'm happy to look into it if you submit a failing test. However, this looks more like an npm install issue and should be discussed at https://npm.community/c/support.
