### ISSUE TITLE
always undefined 

### ISSUE THREAD

**Issue by cruisemiraz** [sindresorhus/active-win#78]
I am just a newbie on electron , wanted to make this work for me 

My renderer.js  

```
const activeWin = require('active-win').promises;
console.log(activeWin)
```

shows : undefined  in console 

thats all , how should i get the current window name 

i run " npm start" and it shows my electron application window
inside developer tools i see my console

while keeping the app open , when i open browser , the console still shows undefined

I know i am missing something 

any help would be appreciated , thank you

**Comment by cruisemiraz** [comment]
i am using 

**const activeWin = require('active-win');
 
activeWin().finally(result => {
    console.log(result);
   
});**

and getting below error

`const activeWin = require('active-win');
 
activeWin().finally(result => {
    console.log(result);
   
});
`

**Comment by cruisemiraz** [comment]
issue resolved ...

**Comment by dougpagani** [comment]
@cruisemiraz can you share what resolved it for you? Otherwise you're looking like [denvercoder](https://xkcd.com/979/)
