### ISSUE TITLE
Error Buffer, how to resolve?

### ISSUE THREAD

**Issue by joubertsaquett** [sindresorhus/active-win#79]
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

package.json

  "devDependencies": {
    "electron": "^9.1.2",
    "electron-rebuild": "^1.11.0"
  },
  "dependencies": {
    "active-win": "^6.1.0",
    "electron-active-window": "0.0.4",
    "ffi-napi": "^2.4.5",
    "iconv": "^3.0.0",
    "ps-list": "^7.2.0",
    "ref-napi": "^1.4.2",
    "ref-struct-napi": "^1.1.0",
    "ref-wchar-napi": "^1.0.2"
  }

node => v10.22.0
npm => 6.14.1

**Comment by sindresorhus** [comment]
This package doesn't use `Buffer()` anywhere. It might come from a sub-dependency, and if so, you'll have to open an issue there instead.
