### ISSUE TITLE
error in Electron 9 on MacOS 10.15.5

### ISSUE THREAD

**Issue by apiashko** [sindresorhus/active-win#81]
1. get stock quickstart electron https://www.electronjs.org/docs/tutorial/first-app#trying-this-example
2. add after createWindow() call
     let aw = activeWin.sync();
     console.log("+++", aw);
3. error:
 ```
(node:15985) UnhandledPromiseRejectionWarning: Error: Command failed: ...../electron-quick-start/node_modules/active-win/main
    at checkExecSyncError (child_process.js:630:11)
    at Object.execFileSync (child_process.js:648:15)
    at Object.func [as execFileSync] (electron/js2c/asar.js:140:31)
    at AsyncFunction.module.exports.sync (...../electron-quick-start/electron-quick-start/node_modules/active-win/lib/macos.js:27:51)
    at Function.module.exports.sync (...../electron-quick-start/node_modules/active-win/index.js:21:33)
    at ...../electron-quick-startelectron-quick-start/main.js:28:22
```
(node:15985) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15985) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

environment:
 Node.js 12.14.1, Chromium 83.0.4103.122, and Electron 9.2.0.

**Comment by apiashko** [comment]
update, it works if I downgrade
`npm install active-win@^5.0.0`

**Comment by sindresorhus** [comment]
This is a Node.js package. You are free to use it with Electron, but this is not the place to ask for Electron-related support. The problem is most likely how you build your app and that the binary does not get included.
