### ISSUE TITLE
Add .url functionality for Windows

### ISSUE THREAD

**Issue by Nikolassparrow** [sindresorhus/active-win#85]
why is it only a thing for macOS users? Could .url be added for windows as well?

**Comment by sindresorhus** [comment]
Duplicate of #64

**Comment by sindresorhus** [comment]
It's simplify because no one added it.

**Comment by Nikolassparrow** [comment]
could it be added then..?

**Comment by sshah-tilaka** [comment]
Dear Sindre Sorhus, I wanted to ask you if there are plans to make the "url" work on Windows platform? Thanks, Sunny
