### ISSUE TITLE
Window title is blank

### ISSUE THREAD

**Issue by AmonWarner** [sindresorhus/active-win#87]
I'm on macos Catalina, And it gets all the active windows correct except for the window title. how do I get the window title? right now it's just blank. I can provide more if needed

**Comment by sindresorhus** [comment]
Getting the window title requires permission. You should either have gotten a prompt or an error message:

https://github.com/sindresorhus/active-win/blob/598e9a937e178342e8d742f89e66afdf7e785da8/Sources/active-win/main.swift#L14-L18

**Comment by AmonWarner** [comment]
I'll take a look. Thanks!
