### ISSUE TITLE
Allow opting out of triggering access dialogs

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/active-win#88]
https://github.com/sindresorhus/active-win/pull/67

**Comment by wrgoto** [comment]
This could be really helpful to me. Is it also possible to opt-out of the screen recording permission if we do not need the title? I'm not familiar with Swift, but would be happy to sponsor the change if possible.

**Comment by achuinard** [comment]
PR #67 was a good start for this but seems to be abandoned. I (am trying to) use this library in a `setInterval` and it's totally unusable it its current state.

**Comment by wrgoto** [comment]
@achuinard We use active-win in a `setInterval` type behavior. Before triggering any interval behavior, it helps to ask for macOS permissions upfront. You might want to take a look at:

https://github.com/karaggeorge/macos-accessibility-permissions
https://github.com/karaggeorge/mac-screen-capture-permissions

I'm going to work on getting something like PR #67 but maybe just limited to the screen recording permissions.

**Comment by achuinard** [comment]
I, too, am using setInterval with a simple fork that removes the accessibility check, since I don't need the screen title, just the app name.

**Comment by wrgoto** [comment]
See: https://github.com/sindresorhus/active-win/pull/96

**Comment by wrgoto** [comment]
@sindresorhus bump https://github.com/sindresorhus/active-win/pull/96

**Comment by sindresorhus** [comment]
Done in https://github.com/sindresorhus/active-win/pull/177
