### ISSUE TITLE
Trying to use it with Chrome Ext : Module not found: Error: Can't resolve 'child_process' 

### ISSUE THREAD

**Issue by roysom007** [sindresorhus/active-win#91]
> next build && next export

Loaded env from \app\.env
info  - Creating an optimized production build
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in 'E:\TajProjects\ACE\3_48\21112020_mywork\aptask-extension\app\node_modules\active-win\lib'

> Build error occurred
Error: > Build failed because of webpack errors
    at build (E:\TajProjects\ACE\3_48\21112020_mywork\aptask-extension\app\node_modules\next\dist\build\index.js:15:918)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aptask-extension@0.1.0 export: `next build && next export`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aptask-extension@0.1.0 export script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Computer\AppData\Roaming\npm-cache\_logs\2020-11-27T19_02_24_715Z-debug.log

**Comment by sindresorhus** [comment]
It's a Node.js package. You cannot use it in a browser.
