### ISSUE TITLE
Can't Detect Focusing on Steam (Result undefined)

### ISSUE THREAD

**Issue by haxtordotid** [sindresorhus/active-win#94]
Hey i try focusing on Steam the result is undefined , when i launch & focus to game it can detect game i running
is any explanation why can't detect when focusing on steam 

My thought because is not have title? or Since steam is Browser?

OS: Ubuntu 18.04

**Comment by tkainrad** [comment]
Did you install Steam via Flatpak? Then your issue could now be fixed with [7.5.1](https://github.com/sindresorhus/active-win/releases/tag/v7.5.1).
